export const listings = [
  {
    project_type: "Reforestation",
    country: "Brazil",
    standard: "VCS",
    vintage: 2021,
    qty: 1200,
    ask_price: 14.5,
    rating_grade: "A",
    suggested_price: 13.8,
  },
  {
    project_type: "Renewable Energy",
    country: "India",
    standard: "Gold Standard",
    vintage: 2020,
    qty: 850,
    ask_price: 12.0,
    rating_grade: "B+",
    suggested_price: 11.4,
  },
  {
    project_type: "Cookstoves",
    country: "Kenya",
    standard: "Verra",
    vintage: 2019,
    qty: 1500,
    ask_price: 9.75,
    rating_grade: "A-",
    suggested_price: 10.1,
  },
];
